### ISSUE TITLE
Need help.. Input text with autocomplete is not working in IE 10

### ISSUE THREAD

**Issue by visensa** [diy/jquery-placeholder#11]
I experienced an issue "Member Not Found" when running on IE 10. After I looked into more further on my code, the autocomplete is the code that causing the issue. I used the autocomplete for my SlickGrid. Any help will be appreciate

Thank you

**Comment by brianreavis** [comment]
@thisandagain Could you merge this pull request?

**Comment by thisandagain** [comment]
All set. Thanks for the patch @brianreavis !
