### ISSUE TITLE
jquery.placeholder unsets any webfont declarations on the page (not just on inputs/placeholders)

### ISSUE THREAD

**Issue by juanojeda** [diy/jquery-placeholder#18]
I had a weird issue where using this plugin (the minified version) was causing my webfonts to fallback to the default Arial (or whatever was set before the webfont).

Not entirely sure why it's happening, but removing the 'font-family' property from the css property fixes it.

The original:
`... h="-moz-box-sizing -webkit-box-sizing box-sizing padding-top padding-right padding-bottom padding-left margin-top margin-right margin-bottom margin-left border-top-width border-right-width border-bottom-width border-left-width line-height font-size font-family width height top left right bottom"...`

becomes:
`... h="-moz-box-sizing -webkit-box-sizing box-sizing padding-top padding-right padding-bottom padding-left margin-top margin-right margin-bottom margin-left border-top-width border-right-width border-bottom-width border-left-width line-height font-size width height top left right bottom"...`

This just means you have to explicitly set the font-family on the .placeholder class.

**Comment by brianreavis** [comment]
Hmm, can you give me more info on how to reproduce the behavior you were encountering? Browser info and how you were using the placeholder plugin would be helpful.

**Comment by juanojeda** [comment]
Yep, apologies for the vague report.

The bug manifests in ie8 (I didn't test below this, as it isn't required for our project).

Initially the page loads with webfonts rendering fine. Once you hover on an element containing webfont'd text, all webfonts fall back to standard fonts.

This is how I loaded/initialized it:

```
Modernizr.load({
    test: Modernizr.input.placeholder,
    nope: '/Scripts/jquery.placeholder.min.js',
    complete: function(){
        $(document).ready(function(){
            if(!Modernizr.input.placeholder){
                $('input, textarea').placeholder();
            }
        })
    }
});
```

**Comment by brianreavis** [comment]
I'm assuming you're using webfonts on your input elements?

Can you give this a try? http://stackoverflow.com/questions/9809351/ie8-css-font-face-fonts-only-working-for-before-content-on-over-and-sometimes#answer-10079790

``` html
<link rel="stylesheet" href="/stylesheets/main.css" type="text/css">
<!--[if lt IE 9]>
<script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
```

Then put "jquery.placeholder.js" (and your code that calls it) _after_ the HTML5 shiv.
