### ISSUE TITLE
Why is the demoversion of the script different than the repo version?

### ISSUE THREAD

**Issue by shapeshifta78** [diy/jquery-placeholder#23]
I'd like to use hideOnInput, but it is just in the demoversion? Why? ;)

**Comment by thisandagain** [comment]
I'm not sure what you are referring to... the example index.html or the readme?

**Comment by shapeshifta78** [comment]
Hi there!

http://diy.github.io/jquery-placeholder/javascripts/jquery.placeholder.js is not the same as 
https://github.com/diy/jquery-placeholder/blob/master/jquery.placeholder.js

The latter one seems to be missing support for hideOnInput or am I just to blind to see it.

Regards,
Tom
