### ISSUE TITLE
Minimum jQuery version

### ISSUE THREAD

**Issue by jmoralesv** [diy/jquery-placeholder#5]
Hi,
This is not an issue actually. I've just seen that this plugin doesn't work with jQuery versions lower than 1.7. Will it be available a version which work with 1.5 or 1.6? In my project I can't update the jQuery plugin, and I don't want to modify the plugin's code and mess it up.

Thanks for your reply.

**Comment by brianreavis** [comment]
Adding support for the now-deprecated features of jQuery will introduce cruft, so I'd really like to avoid doing it.

If you replace `.on(` with `.bind(` it should be work just fine with 1.5 / 1.6 and not break anything :)

**Comment by jmoralesv** [comment]
Hi Brian,
Thanks for your answer. Yes, I have done that and it seems to work.  However, the textboxes I'm using have a jQuery UI calendar picker attached, and when I select a date in the calendar, the date shows messed up with the text of the placecholder. This occurs the first time the calendar is opened.

It looks like that I need to fire an event when the value of the texbox is changed by javascript (like jQuery UI calendar does) but I don't know where or how to do it.

Thanks.
